# IMPORTING PACKAGES

In [1]:
import numpy as np

# ASSIGNMENT 1 - ARRAY BASICS

Can you import Numpy and convert the following list comprehension (I  jjust learned about compreshensions in an awesome course by Maven) in an array? 
Once you've done that  , report the dimenesions ,  shape  ,size and dtype.

In [3]:
array = np.array([x * 10 for x in range(1,11)])

In [4]:
# ndim  , shape , size  and dtype

print(f"The dimenssion of array : {array.ndim}")
print(f"shape of the array : {array.shape}")
print(f"size of the array : {array.size}")
print(f"data type of the array :  {array.dtype}")

The dimenssion of array : 1
shape of the array : (10,)
size of the array : 10
data type of the array :  int64


# ASSIGNEMENT 2 

Does Numpy have anything like the range() function from base python? 

If so , create the same array from assignement 2 using a Numpy function. But make it 5 rows and 2 columns. it's ok if the datatype is float or int

In [7]:
array = np.linspace(10 , 100 , 10 , dtype = int).reshape(5 , 2)
print(array)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [11]:
array = np.arange(10 , 110, 10 , dtype = int).reshape(5 , 2)
print(array)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [17]:
array  = (np.arange(1,11)*10).reshape(5,2)
array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

### CAN YOU CREATE A 3X3 ARRAY OF RANDOM NUMBERS BETWEEN 0  TO  1 USE A RANDOM STATE OF 2022 

In [3]:
rng = np.random.default_rng(2022)
array = rng.random((3,3))
print(array)

[[0.24742606 0.09299006 0.61176337]
 [0.06066207 0.66103343 0.75515778]
 [0.1108689  0.04305584 0.41441747]]


# Assignment 3 
Slice and index the 'random_array' we created in the previous exercise . Perform the following exercises : 

 - Grab the first two 'rows' of the array 
 - Grab the entire first column
 - Then grab the second element of the third row
 

In [8]:
print(array[:2])

[[0.24742606 0.09299006 0.61176337]
 [0.06066207 0.66103343 0.75515778]]


In [9]:
print(array[ : , 0 ])

[0.24742606 0.06066207 0.1108689 ]


In [11]:
print(array[2 , 1 ])

0.04305584439252108


# Assignment 4 

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices  below.

Before we do that  , we want to add a 5 dollar shipping fee that will be calculated before the disocount is applied. Call this array total.

- Once we have that ,  we want to use the random_array /array ,  reshape it to one dimension , Call this discount_pct.
- Substract discount_pct FROM 1 , store this in pct_owed.
- Multiply pct_owed by total to get the final amount owed.

In [13]:
prices = np.array([5.99 , 6.99 , 22.49 , 99.99 , 4.99 , 49.99])

total = prices + 5

total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [19]:
discount_pct = array[:2 , :].reshape(6)

pct_owed = 1 - discount_pct

final_owed = pct_owed * total

final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

In [22]:
((1-(array[:2 , :].reshape(6))) * total).round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

In [25]:
print(discount_pct)
print(pct_owed)
print(final_owed)

[0.24742606 0.09299006 0.61176337 0.06066207 0.66103343 0.75515778]
[0.75257394 0.90700994 0.38823663 0.93933793 0.33896657 0.24484222]
[ 8.27078756 10.87504916 10.67262487 98.6210889   3.38627605 13.4638738 ]


# Assignment 5
Filter the product to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. Store the elements returned in an array called ``` fancy_feast_special ```

Next , create a shipping cost array where the cost is 0 if price is greater than 20 , and 5 if not.


In [4]:
products = np.array(["salad" , "bread" , "mustard" , "rare tomato" , "cola" , "gourmet ice cream"])
prices = np.array([5.99 , 6.99 , 22.49 , 99.99 , 4.99 , 49.99])

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [17]:
# filtering the products that price is greater than 25. 

products[prices > 25.00]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [18]:
# adding cola 

mask = (prices > 25.00) | (products == 'cola')

fancy_feast_special = products[mask]

fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [21]:
# shipping cost array

shipping_cost = np.where(prices > 20 , 0 , 5)

shipping_cost

array([5, 5, 0, 0, 5, 0])

# Assignment 6

First grab the top 3 highest priced items in our list.

Then , calculate the mean , min , max and median of the top three prices.

Finally calculate the numbe of unique price tiers in our ```price_tiers``` array.

In [2]:
prices = np.array([5.99 , 6.99 , 22.49 , 99.99 , 4.99 , 49.99])

prices.sort()

In [3]:
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [6]:
top3 = prices[-3:]

top3

array([22.49, 49.99, 99.99])

In [9]:
print(f"Mean : {top3.mean()}")
print(f"Min : {top3.min()}")
print(f"Max : {top3.max()}")
print(f"Median : {np.median(top3)}")

Mean : 57.49
Min : 22.49
Max : 99.99
Median : 49.99


In [10]:
price_tiers = np.array(['budget' , 'budget' , 'mid-tier' , 'luxury','mid-tier' ,'luxury'])

In [11]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7 : Bring it all together

Our data scientist provided the code to read in a csv as a Pandas dataframe , and has converted the two columns of interest to arrays 

We want to filter our sales series down to only sales where the product family was produce. 

Once you've done that , randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

Finally create a new array that has the values 'abover_both' , 'above_median' and 'below_both'.based on whether the sales were above the median of the sample or below both the mean of the sample.

In [1]:
import pandas as pd
import numpy as np

In [13]:
# Reading csv file

retail_df = pd.read_csv('../DATASETS/retail_2016_2017.csv' , skiprows=range(1,11000) , nrows=1000)

retail_df

id        date  store_nbr               family    sales  onpromotion
0    1956943  2016-01-07         18                 EGGS   177.00            0
1    1956944  2016-01-07         18         FROZEN FOODS    36.00            0
2    1956945  2016-01-07         18            GROCERY I  2291.06            6
3    1956946  2016-01-07         18           GROCERY II    16.00            0
4    1956947  2016-01-07         18             HARDWARE     2.00            0
..       ...         ...        ...                  ...      ...          ...
995  1957938  2016-01-07         45   HOME AND KITCHEN I    83.00            0
996  1957939  2016-01-07         45  HOME AND KITCHEN II    97.00            1
997  1957940  2016-01-07         45      HOME APPLIANCES     1.00            0
998  1957941  2016-01-07         45            HOME CARE   510.00            1
999  1957942  2016-01-07         45           LADIESWEAR     4.00            0

[1000 rows x 6 columns]

In [14]:
family_array = np.array(retail_df['family'])

family_array

array(['EGGS', 'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD', 'AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES',
       'BOOKS', 'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY',
       'DELI', 'EGGS', 'FROZEN FOODS', 'GROCERY I', 'GROCERY II',
       'HARDWARE', 'HOME AND KITCHEN I', 'HOME AND KITCHEN II',
       'HOME APPLIANCES', 'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN',
       'LINGERIE', 'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS',
       'PERSONAL CARE', 'PET SUPPLIES', 'PLAYERS AND ELECTRONICS',
       'POULTRY', 'PREPARED FOODS', 'PRODUCE',
       'SCHOOL AND OFFICE SUPPLIES', 'SEAFOOD', 'AUTOMOTIVE', 'BABY CARE',
       'BEAUT

In [15]:
sales_array = np.array(retail_df['sales'])

sales_array

array([1.77000000e+02, 3.60000000e+01, 2.29106000e+03, 1.60000000e+01,
       2.00000000e+00, 1.20000000e+01, 7.00000000e+00, 0.00000000e+00,
       1.94000000e+02, 3.00000000e+00, 2.00000000e+00, 6.00000000e+00,
       4.60000000e+01, 1.00000000e+00, 2.18416000e+02, 1.84000000e+02,
       4.00000000e+00, 1.00000000e+00, 2.63230000e+02, 5.10000000e+01,
       1.66239400e+03, 0.00000000e+00, 6.53600030e+00, 1.00000000e+01,
       0.00000000e+00, 2.00000000e+00, 3.03300000e+03, 0.00000000e+00,
       1.61000000e+02, 1.20000000e+01, 7.18000000e+02, 2.67000000e+02,
       2.80000000e+02, 2.70000000e+01, 4.70000000e+01, 2.45300000e+03,
       2.00000000e+00, 1.00000000e+00, 2.20000000e+01, 8.00000000e+00,
       0.00000000e+00, 1.39000000e+02, 1.00000000e+00, 0.00000000e+00,
       2.00000000e+00, 4.60000000e+01, 1.00000000e+00, 1.68847000e+02,
       1.90000000e+02, 0.00000000e+00, 0.00000000e+00, 2.18873000e+02,
       4.60000000e+01, 4.47064000e+02, 0.00000000e+00, 4.00000000e+00,
      

In [18]:
produce_array = np.array(sales_array[family_array == 'PRODUCE'])

produce_array

array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [19]:
# random

rng = np.random.default_rng(2022)

random_array = rng.random(produce_array.size)

random_array

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747, 0.98862926,
       0.96919869, 0.25697153, 0.55876211, 0.24234798, 0.32202029,
       0.89135975, 0.94611366, 0.72253931, 0.92847437, 0.99608701,
       0.2494223 , 0.06229007, 0.94479027, 0.65028587, 0.32167568,
       0.08336384, 0.21924361, 0.08417791, 0.05213927, 0.20525022])

In [26]:
sampled_array = produce_array[random_array < .5]

sampled_array

array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [27]:
# finding the mean
mean = np.mean(sampled_array)

mean 


np.float64(2268.102470588235)

In [28]:
median = np.median(sampled_array)

median

np.float64(1272.755)

In [30]:
margin = np.where( 
    sampled_array < median , "below_both" , 
    np.where(sampled_array > mean , "above_both" , "above_median")
)

margin

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')