# Array Operations

In [1]:
import numpy as np

rng = np.random.default_rng(616)
inventory = rng.integers(0 , 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [7]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

In [8]:
(inventory / 2).dtype

dtype('float64')

In [9]:
price = (rng.random(10) * 10 ).round(2)

price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [12]:
total_sum = (price * inventory).sum()

total_sum

np.float64(2520.4700000000003)

In [18]:
# converting the numpy array into a list 
inventory_list = list(inventory)
price_list = list(price) 

print(inventory_list)
print(price_list)

[np.int64(39), np.int64(39), np.int64(93), np.int64(86), np.int64(48), np.int64(46), np.int64(48), np.int64(30), np.int64(11), np.int64(57)]
[np.float64(0.89), np.float64(8.82), np.float64(7.32), np.float64(7.32), np.float64(5.62), np.float64(3.4), np.float64(0.63), np.float64(3.57), np.float64(2.03), np.float64(4.31)]


In [14]:
[x * y for x , y in zip(inventory_list , price)]

[np.float64(34.71),
 np.float64(343.98),
 np.float64(680.76),
 np.float64(629.52),
 np.float64(269.76),
 np.float64(156.4),
 np.float64(30.240000000000002),
 np.float64(107.1),
 np.float64(22.33),
 np.float64(245.67)]

# Filtering 

In [2]:
array = np.arange(20)

array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
array % 2 == 0 

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [4]:
array[array % 2 == 0 ]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
even_odd = np.array(['even' , 'odd'] * 10)

even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [9]:
even_odd[even_odd !='odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [15]:
array[even_odd!='odd'] = 0

array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [17]:
mask = (even_odd != 'even') | (even_odd != 'odd' )

mask 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [19]:
array[mask]

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])