## CREATING ARRAYS

In [1]:
import numpy as np

In [2]:
# ones 
np.ones(5 , dtype=int)

array([1, 1, 1, 1, 1])

In [3]:
# zeros
np.zeros(5 , dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
# reshpae
np.zeros((5,2) , dtype=int).reshape(2 , 5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### numpy.arange([start,] stop, [step,] dtype=None) 

In [7]:
np.arange(10 , 100 , 10 , dtype = int )

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
| Parameter  | Description                                          |
| ---------- | ---------------------------------------------------- |
| `start`    | Start of the interval                                |
| `stop`     | End of the interval                                  |
| `num`      | Number of points to generate (default = 50)          |
| `endpoint` | If True, include `stop` in the output                |
| `retstep`  | If True, return (`array`, `step`)                    |
| `dtype`    | Output data type                                     |
| `axis`     | The axis in the result along which values are stored |

| Parameter        | Formula for Step                             |
| ---------------- | -------------------------------------------- |
| `endpoint=True`  | $\frac{\text{stop} - \text{start}}{num - 1}$ |
| `endpoint=False` | $\frac{\text{stop} - \text{start}}{num}$     |


step = stop - start / (num - 1)  , ## if endpoint is true

step = stop - start / num ## if endpoint is false

In [8]:
np.linspace(10 , 100 , 10 , dtype = int)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Random Number generation

In [10]:
rng = np.random.default_rng(616)

rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [17]:
rng.integers(0 , 10 , 100)

array([8, 4, 8, 9, 7, 7, 9, 0, 7, 2, 0, 6, 0, 2, 1, 9, 7, 0, 0, 8, 9, 4,
       9, 2, 0, 4, 4, 6, 9, 5, 7, 5, 9, 4, 8, 6, 0, 9, 9, 8, 9, 9, 6, 9,
       3, 6, 4, 4, 5, 3, 8, 1, 1, 8, 1, 9, 8, 1, 5, 6, 0, 6, 3, 7, 2, 8,
       3, 0, 5, 5, 4, 7, 3, 3, 2, 7, 4, 7, 0, 6, 0, 2, 6, 2, 1, 5, 9, 1,
       7, 6, 9, 3, 2, 7, 5, 6, 3, 0, 0, 6])

In [19]:
rng.integers(5)

np.int64(2)

rng.normal(loc=0.0, scale=1.0, size=None)
| Parameter | Description                                     |
| --------- | ----------------------------------------------- |
| `loc`     | Mean (center of the distribution)               |
| `scale`   | Standard deviation (spread of the distribution) |
| `size`    | Shape/number of random values to generate       |


In [20]:
rng.normal(50 , 5 , 10)

array([52.75076308, 54.97167104, 59.95036699, 51.75676495, 52.4340682 ,
       56.19249833, 49.82502727, 45.8219855 , 45.99913101, 43.15965948])