# Array aggregation methods

min , max , mean , sum

In [1]:
import numpy as np

rng = np.random.default_rng(616)
inventory = rng.integers(0 , 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [5]:
price = (rng.random(10) * 10 ).round(2)

price.sort()

In [6]:
price.mean()

np.float64(4.391)

argmin() , argmax()

This will be returning the index

In [7]:
(inventory * price).argmax()

np.int64(2)

In [10]:
price_2d = price.reshape((5,2))

price_2d

array([[0.89, 8.82],
       [7.32, 7.32],
       [5.62, 3.4 ],
       [0.63, 3.57],
       [2.03, 4.31]])

In [11]:
# accross rows
price_2d.sum(axis =0 )

array([16.49, 27.42])

In [12]:
# accross the columns
price_2d.sum(axis = 1)

array([ 9.71, 14.64,  9.02,  4.2 ,  6.34])

In [6]:
reshaped = price.reshape((2,5))

reshaped

array([[0.3 , 0.75, 1.03, 1.51, 5.24],
       [6.63, 7.26, 7.66, 8.02, 8.97]])

In [8]:
np.median(reshaped )

np.float64(5.9350000000000005)

In [10]:
np.percentile(reshaped , 50)

np.float64(5.9350000000000005)

In [11]:
np.sqrt(reshaped)

array([[0.54772256, 0.8660254 , 1.01488916, 1.22882057, 2.28910463],
       [2.57487864, 2.69443872, 2.7676705 , 2.83196045, 2.99499583]])

In [12]:
np.unique(reshaped)

array([0.3 , 0.75, 1.03, 1.51, 5.24, 6.63, 7.26, 7.66, 8.02, 8.97])

In [14]:
np.unique(np.ones(1000 , dtype='int'))

array([1])