## Indexing & Slicing 

### 1D Array

In [1]:
import numpy as np

In [4]:
array = np.arange(12)

array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
array[3]

np.int64(3)

In [6]:
array[2:7]

array([2, 3, 4, 5, 6])

In [8]:
array[::2]

array([ 0,  2,  4,  6,  8, 10])

## 2D Array
``` arr[row_start:row_end, column_start:column_end] ``` 


In [12]:
new_array = array.reshape((3,4))

new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
new_array[: , :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
new_array[1:, : ]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
new_array[1 , 3]

np.int64(7)